### ISSUE TITLE
fedpkg update fails with traceback

### ISSUE THREAD

**Issue by nirik** [fedora-infra/python-fedora#158]
```
% fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
Creating a new update for  ansible-1.9.4-1.fc23 
Password: 
```
```python
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 80, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 155, in save
    kwargs['csrf_token'] = self.csrf()
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 80, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 308, in csrf
    'csrf', verb='GET', auth=True)['csrf_token']
KeyError: 'csrf_token'
Could not generate update request: Command 'bodhi --new --release f23 --file bodhi.template ansible-1.9.4-1.fc23 --username kevin' returned non-zero exit status 1
```
python-fedora-0.6.0-1.fc24.noarch

**Comment by ralphbean** [comment]
I'm not 100% sure, but I think this may be due to an error on ipsilon's side.

Trying to hack through this, I encountered consistent 500 error codes coming from the openidbaseclient calls to ipsilon.

Checking the ipsilon server logs, I see this:

```python
[11/Oct/2015:01:01:26] HTTP 
Request Headers:
  X-FORWARDED-SERVER: id.fedoraproject.org
  COOKIE: fedora_ipsilon_session_id=SCRUBBED_OUT_BY_THREEBEAN
  X-FORWARDED-HOST: id.fedoraproject.org
  X-FORWARDED-SCHEME: https
  Content-Length: 1054
  USER-AGENT: python-requests/2.7.0 CPython/2.7.10 Linux/4.1.10-200.fc22.x86_64
  Remote-Addr: SCRUBBED_OUT_BY_THREEBEAN
  HOST: localhost:10020
  ACCEPT: */*
  X-FORWARDED-FOR: SCRUBBED_OUT_BY_THREEBEAN
  Content-Type: application/x-www-form-urlencoded
  ACCEPT-ENCODING: gzip, deflate
[11/Oct/2015:01:01:26] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/ipsilon/util/page.py", line 91, in __call__
    return op(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ipsilon/providers/openid/extensions/api.py", line 45, in root
    return json.dumps(self._perform_call(kwargs))
  File "/usr/lib/python2.7/site-packages/ipsilon/providers/openid/extensions/api.py", line 72, in _perform_call
    username = arguments['username']
KeyError: 'username'
```

Not sure if this is due to a change in python-fedora **or** if this is due to any of the recent changes in the python-openid package on the ipsilon servers.  Will have to ask @puiterwijk.

**Comment by puiterwijk** [comment]
This traceback indicates that the original request to the api endpoint did not contain a userid argument in the json.

Can you give me a (sanitized) json blob you're sending to the API?
